
@server = http://localhost:8080

###
GET {{server}}
###
GET {{server}}/instrumentos
###
POST {{server}}/instrumentos
Content-Type: application/json

{"nombre": "Trompeta"}

##################

GET {{server}}/categorias
###
POST {{server}}/categorias
Content-Type: application/json

{"nombre":"Aire"}